SET LINESIZE 32767
SET PAGESIZE 50000
SET COLSEP '|'
SET TRIMSPOOL ON
SET WRAP OFF
SELECT VSUES_CD, VSUES_DS, VPRRE_DS
FROM (
    SELECT VSUES_CD, VSUES_DS, VPRRE_DS,
           ROW_NUMBER() OVER (PARTITION BY VPRRE_DS, VSUES_DS ORDER BY VPRRE_DS, VSUES_DS) AS rn
    FROM v_app_subesp
    WHERE {where_clause}
)
WHERE rn <= 3
{order_by};